### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by martenreeh** [selpoG/autoboot#7]
**Describe the bug**
If I run Ising.m in sample it gives an error and not the correct output. The O2 example does work well.

**To Reproduce**
Run Ising.m. See error.  (Specifically bootstrapAll[] gives an error.)

**Expected behavior**
Output crossing equations. Not give an error. 

 - OS: Ubuntu 18.04
 - Mathematica Version "12.0.0 for Linux x86 (64-bit) (April 7, 2019)"

**Comment by selpoG** [comment]
I think that this is not a bug; please [execute `tar xvf sgd.tar.xz`](https://github.com/selpoG/autoboot#setup).
`getGroup[g, id]` searches `sgd/sg.<g>.<id>.m`, and if it does not exist, then return `Null` (this is confusing, so I'm planning to just abort).
`sample/Ising.m` needs `sgd/sg.2.1.m`, which is included in `sgd.tar.xz`.

**Comment by martenreeh** [comment]
Thanks. My mistake. Did not execute `tar xvf sgd.tar.xz.`
